# Customization
dconf write "/org/gnome/desktop/background/show-desktop-icons" "false"
dconf write "/org/gnome/desktop/calendar/show-weekdate" "false"
dconf write "/org/gnome/desktop/default-applications/terminal/exec" "'alacritty'"
dconf write "/org/gnome/desktop/default-applications/terminal/exec-arg" "false"
dconf write "/org/gnome/desktop/input-sources/sources" "['xkb', 'us']"
dconf write "/org/gnome/desktop/input-sources/xkb-options" "['compose:ralt', 'caps:swapescape', 'terminate:ctrl_alt_bksp', 'mod_led:compose']"
dconf write "/org/gnome/desktop/interface/color-scheme" "'prefer-dark'"
dconf write "/org/gnome/desktop/interface/show-battery-percentage" "true"
dconf write "/org/gnome/desktop/interface/clock-format" "'24h'"
dconf write "/org/gnome/desktop/interface/clock-show-date" "true"
dconf write "/org/gnome/desktop/interface/clock-show-seconds" "false"
dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
dconf write "/org/gnome/desktop/interface/enable-hot-corners" "false"
dconf write "/org/gnome/desktop/peripherals/keyboard/numlock-state" "true"
dconf write "/org/gnome/desktop/peripherals/touchpad/tap-to-click" "true"
dconf write "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" "true"
dconf write "/org/gnome/desktop/privacy/remember-recent-files" "true"
dconf write "/org/gnome/desktop/session/idle-delay" "900"
dconf write "/org/gnome/desktop/wm/keybindings/close" "['<Alt>F4']"
dconf write "/org/gnome/desktop/wm/keybindings/maximize" "['<Super>Up']"
dconf write "/org/gnome/desktop/wm/keybindings/minimize" "['<Super>Down']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-left" "['<Control><Shift><Alt>Left']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-right" "['<Control><Shift><Alt>Right']"
dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Alt>F2']"
dconf write "/org/gnome/desktop/wm/keybindings/show-desktop" "['<Super>d']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-applications" "['<Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-applications-backwards" "['<Shift><Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left" "['<Control><Alt>Left']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right" "['<Control><Alt>Right']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-windows" "['<Alt>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-windows-backwards" "['<Shift><Alt>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/toggle-fullscreen" "['F11']"
dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'appmenu:minimize,maximize,close'"
dconf write "/org/gnome/mutter/workspaces-only-on-primary" "false"
dconf write "/org/gnome/mutter/edge-tiling" "true"
dconf write "/org/gnome/system/location/enabled" "false"
dconf write "/org/gtk/gtk4/settings/file-chooser/date-format" "'regular'"
dconf write "/org/gtk/gtk4/settings/file-chooser/location-mode" "'path-bar'"
dconf write "/org/gtk/gtk4/settings/file-chooser/show-size-column" "true"
dconf write "/org/gtk/gtk4/settings/file-chooser/sort-column" "'name'"
dconf write "/org/gtk/gtk4/settings/file-chooser/sort-order" "'ascending'"
dconf write "/org/gtk/gtk4/settings/file-chooser/sort-directories-first" "true"
dconf write "/org/gtk/gtk4/settings/file-chooser/show-hidden" "true"
dconf write "/org/gtk/gtk4/settings/file-chooser/view-type" "'list'"

# Keybindings
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding" "'<Control><Alt>t'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command" "'ghostty'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name" "'Terminal'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding" "'<Control><Alt>f'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command" "'/usr/bin/env nautilus'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name" "'File Manager'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding" "'<Control><Alt>b'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command" "'flatpak run com.bitwarden.desktop'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name" "'Password Manager'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings" "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

# Extensions
dconf write "/org/gnome/shell/enabled-extensions" "['blur-my-shell@aunetx', 'gSnap@micahosborne', 'AlphabeticalAppGrid@stuarthayhurst', 'notification-timeout@chlumskyvaclav.gmail.com']"
# Extension Configuration
dconf write "/org/gnome/shell/extensions/alphabetical-app-grid/folder-order-position" "'end'"
dconf write "/org/gnome/shell/extensions/alphabetical-app-grid/sort-folder-contents" "true"
dconf write "/org/gnome/shell/extensions/gsnap/use-modifier" "true"
dconf write "/org/gnome/shell/extensions/gsnap/span-multiple-zones" "true"
dconf write "/org/gnome/shell/extensions/gsnap/window-margin" "5"
dconf write "/org/gnome/shell/extensions/notification-timeout/ignore-idle" "false"
dconf write "/org/gnome/shell/extensions/notification-timeout/always-normal" "true"
dconf write "/org/gnome/shell/extensions/notification-timeout/timeout" "5000"
