name: 'photos'
services:

  # Database Setup
  # ==============
  #   CREATE USER immich WITH ENCRYPTED PASSWORD '<password>';
  #   CREATE DATABASE immich;
  #   \c immich
  #   ALTER DATABASE immich OWNER TO immich;
  #   CREATE EXTENSION vchord CASCADE;
  #   CREATE EXTENSION earthdistance CASCADE;
  server:
    image: 'ghcr.io/immich-app/immich-server:v2.4.1'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          memory: '2G'
    networks:
      - 'cache'
      - 'database'
    environment:
      TZ: 'Europe/Amsterdam'
      IMMICH_ENV: 'production'
      IMMICH_MEDIA_LOCATION: '/data/class2'
      DB_HOSTNAME: 'postgres'
      DB_USERNAME: 'immich'
      DB_PASSWORD_FILE: '/run/secrets/dbpass'
      DB_DATABASE_NAME: 'immich'
      DB_VECTOR_EXTENSION: 'vectorchord'
      DB_STORAGE_TYPE: 'HDD'
      DB_POOL_SIZE: '25'
      REDIS_HOSTNAME: 'valkey'
      # IMMICH_CONFIG_FILE: '/etc/immich/config.json'
    secrets:
      - 'dbpass'
    # configs:
    #   - source: 'immich'
    #     target: '/etc/immich/config.json'
    ports:
      - target: 2283
        published: 2283
        protocol: 'tcp'
    volumes:
      - type: 'bind'
        source: '/mnt/tank4/class1/photos'
        target: '/data/class1'
        read_only: true
      - type: 'bind'
        source: '/mnt/tank4/class2/photos'
        target: '/data/class2'
        read_only: false
      - type: 'bind'
        source: '/mnt/fast/apps/immich'
        target: '/usr/src/app/upload'
        read_only: false
      - type: 'bind'
        source: '/etc/localtime'
        target: '/etc/localtime'
        read_only: true
    devices:
      # Hardware-accelerated Transcoding (N100M)
      - '/dev/dri:/dev/dri'

networks:
  cache:
    external: true
  database:
    external: true

secrets:
  dbpass:
    file: '/mnt/tank4/class1/secrets/postgres/immich'

configs:
  immich:
    content: |
      {
        "backup": {"database": {
          "cronExpression": "0 02 * * *",
          "enabled": false,
          "keepLastAmount": 14
        }},
        "ffmpeg": {
          "accel": "vaapi",
          "accelDecode": true,
          "acceptedAudioCodecs": ["aac", "mp3", "libopus"],
          "acceptedContainers": ["mov", "ogg", "webm"],
          "acceptedVideoCodecs": ["av1"],
          "bframes": -1,
          "cqMode": "auto",
          "crf": 35,
          "gopSize": 0,
          "maxBitrate": "0",
          "preferredHwDevice": "auto",
          "preset": "faster",
          "refs": 0,
          "targetAudioCodec": "aac",
          "targetResolution": "1080",
          "targetVideoCodec": "av1",
          "temporalAQ": false,
          "threads": 0,
          "tonemap": "hable",
          "transcode": "required",
          "twoPass": false
        },
        "image": {
          "colorspace": "p3",
          "extractEmbedded": false,
          "fullsize": {
            "enabled": false,
            "format": "jpeg",
            "quality": 80
          },
          "preview": {
            "format": "jpeg",
            "quality": 80,
            "size": 1440
          },
          "thumbnail": {
            "format": "jpeg",
            "quality": 80,
            "size": 250
          }
        },
        "job": {
          "backgroundTask": {"concurrency": 5},
          "faceDetection": {"concurrency": 1},
          "library": {"concurrency": 3},
          "metadataExtraction": {"concurrency": 3},
          "migration": {"concurrency": 5},
          "notifications": {"concurrency": 5},
          "ocr": {"concurrency": 1},
          "search": {"concurrency": 5},
          "sidecar": {"concurrency": 3},
          "smartSearch": {"concurrency": 1},
          "thumbnailGeneration": {"concurrency": 2},
          "videoConversion": {"concurrency": 1},
          "workflow": {"concurrency": 5}
        },
        "library": {
          "scan": {
            "cronExpression": "0 0 * * *",
            "enabled": true
          },
          "watch": {"enabled": false}
        },
        "logging": {
          "enabled": true,
          "level": "warn"
        },
        "machineLearning": {
          "availabilityChecks": {
            "enabled": true,
            "interval": 900000,
            "timeout": 2000
          },
          "clip": {
            "enabled": true,
            "modelName": "ViT-SO400M-16-SigLIP2-384__webli"
          },
          "duplicateDetection": {
            "enabled": true,
            "maxDistance": 0.05
          },
          "enabled": true,
          "facialRecognition": {
            "enabled": true,
            "maxDistance": 0.5,
            "minFaces": 3,
            "minScore": 0.7,
            "modelName": "antelopev2"
          },
          "ocr": {
            "enabled": true,
            "maxResolution": 736,
            "minDetectionScore": 0.5,
            "minRecognitionScore": 0.8,
            "modelName": "LATIN__PP-OCRv5_mobile"
          },
          "urls": ["http://desktop.lan.zanbaldwin.com:3003"]
        },
        "map": {
          "darkStyle": "https://tiles.immich.cloud/v1/style/dark.json",
          "enabled": true,
          "lightStyle": "https://tiles.immich.cloud/v1/style/light.json"
        },
        "metadata": {"faces": {"import": true}},
        "newVersionCheck": {
          "enabled": true
        },
        "nightlyTasks": {
          "clusterNewFaces": true,
          "databaseCleanup": true,
          "generateMemories": true,
          "missingThumbnails": true,
          "startTime": "04:00",
          "syncQuotaUsage": true
        },
        "notifications": {
          "smtp": {
            "enabled": false,
            "from": "",
            "replyTo": "",
            "transport": {
              "host": "",
              "ignoreCert": false,
              "password": "",
              "port": 587,
              "secure": false,
              "username": ""
            }
          }
        },
        "oauth": {
          "autoLaunch": false,
          "autoRegister": true,
          "buttonText": "Login with OAuth",
          "clientId": "",
          "clientSecret": "",
          "defaultStorageQuota": null,
          "enabled": false,
          "issuerUrl": "",
          "mobileOverrideEnabled": false,
          "mobileRedirectUri": "",
          "profileSigningAlgorithm": "none",
          "roleClaim": "immich_role",
          "scope": "openid email profile",
          "signingAlgorithm": "RS256",
          "storageLabelClaim": "preferred_username",
          "storageQuotaClaim": "immich_quota",
          "timeout": 30000,
          "tokenEndpointAuthMethod": "client_secret_post"
        },
        "passwordLogin": {"enabled": true},
        "reverseGeocoding": {"enabled": true},
        "server": {
          "externalDomain": "https://photos.lan.zanbaldwin.com",
          "loginPageMessage": "",
          "publicUsers": false
        },
        "storageTemplate": {
          "enabled": true,
          "hashVerificationEnabled": true,
          "template": "{{filetypefull}}/{{y}}/{{MM}}-{{MMMM}}/W{{WW}}/{{y}}{{MM}}{{dd}}T{{HH}}{{mm}}{{ss}}-{{filename}}"
        },
        "templates": {
          "email": {
            "albumInviteTemplate": "",
            "albumUpdateTemplate": "",
            "welcomeTemplate": ""
          }
        },
        "theme": {"customCss": ""},
        "trash": {
          "days": 30,
          "enabled": true
        },
        "user": {"deleteDelay": 7}
      }
