name: 'proxy'
services:

  manager:
    image: 'jc21/nginx-proxy-manager:2.13.5'
    restart: 'unless-stopped'
    # Don't bother with extra_hosts, Nginx does not use it. Use host network instead.
    network_mode: 'host'
    healthcheck:
      test: [ 'CMD', '/bin/check-health' ]
      interval: '10s'
      timeout: '3s'
    secrets:
      - 'cloudflare'
    # Technically these are ignored in "host" network mode,
    # but always good to reference them in config.
    ports:
      - target: 80
        published: 80
        protocol: 'tcp'
      - target: 443
        published: 443
        protocol: 'tcp'
      - target: 81
        published: 81
        protocol: 'tcp'
    volumes:
      - type: 'bind'
        source: '/mnt/fast/apps/proxy/config'
        target: '/data'
        read_only: false
      - type: 'bind'
        source: '/mnt/fast/apps/proxy/certs'
        target: '/etc/letsencrypt'
        read_only: false

secrets:
  cloudflare:
    file: '/mnt/tank4/class1/secrets/cloudflare'
