match_block_trailing_comma = true
hard_tabs = false
edition = "2021"
force_explicit_abi = true
max_width = 120
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 80
tab_spaces = 4
use_field_init_shorthand = true
binop_operator = "Front"
chain_width = 80
comment_width = 80
condense_wildcard_suffixes = true
fn_call_width = 80
format_code_in_doc_comments = true
hex_literal_case = "Upper"
indent_style = "Block"