# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$status\
$os\
$username\
$hostname\
$kubernetes\
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$nodejs\
$php\
$python\
$rust\
$terraform\
$vagrant\
$memory_usage\
$aws\
$gcloud\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$container\
$shell\
$character"""
continuation_prompt = "[↳ ](bold white)"

[character]
format = "$symbol "
success_symbol = "[❯](blue)"
error_symbol = "[✖](bold red)"

[status]
format = '[$status]($style) '
style = 'bold red'
disabled = false

[os]
disabled = false
format = "[$symbol ]($style)"
style = "gray"
[os.symbols]
Debian = '󰣚'
Fedora = '󰣛'
Linux = ''
Macos = '󰘳'
Raspbian = ''
Ubuntu = '󰕈'

[username]
show_always = true
format = '[$user]($style)'
disabled = false
style_user = "cyan"
style_root = "red"

[hostname]
disabled = false
ssh_only = false
format = "[@](white dimmed)[$ssh_symbol$hostname]($style)"
style = "green"

[directory]
format = "[ $path]($style)[:](dimmed) "
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
before_repo_root_style = "dimmed cyan"
repo_root_style = "cyan"
style = "cyan"
read_only = ' 🔒'
repo_root_format = " [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)[:](dimmed) "

[fill]
symbol = " "

[sudo]
disabled = false

[git_metrics]
disabled = false

[shell]
disabled = true
[jobs]
disabled = true
[container]
disabled = true
