[net]
git-fetch-with-cli = true

[http]
ssl-version = "tlsv1.3"
multiplexing = true

[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
# Compile for more modern CPU architecture. Work laptop doesn't support v4, though.
rustflags = ["-C", "target-cpu=x86-64-v3"]
