# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$status\
$container\
$username\
$hostname\
$os\
$kubernetes\
$directory\
$fill\
$nix_shell\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
${custom.podman}\
$package\
$nodejs\
$php\
$python\
$rust\
$terraform\
$vagrant\
$memory_usage\
$aws\
$gcloud\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$shell\
$character"""
continuation_prompt = "[↳ ](bold white)"

[character]
format = "$symbol "
success_symbol = "[❯](blue)"
error_symbol = "[×](bold red)"

[status]
format = '[$status]($style) '
style = 'bold red'
disabled = false

[os]
disabled = true
format = "[ $symbol ]($style)"
style = "gray"
[os.symbols]
Debian = '󰣚'
Fedora = '󰌽'
Linux = '󰌽'
Macos = '󰘳'
Raspbian = ''
Ubuntu = '󰕈'

[username]
show_always = true
format = '[$user]($style)'
disabled = false
style_user = "cyan"
style_root = "red"

[hostname]
disabled = false
ssh_only = false
format = "[@](white dimmed)[$ssh_symbol$hostname]($style)"
style = "green"

[directory]
format = "[ $path]($style)[:](dimmed)[$read_only]($read_only_style) "
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
before_repo_root_style = "dimmed cyan"
repo_root_style = "cyan"
style = "cyan"
read_only = ' '
repo_root_format = " [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[:](dimmed)[$read_only]($read_only_style) "

[fill]
symbol = " "

[sudo]
disabled = false

[git_metrics]
disabled = false

[shell]
disabled = true
[nix_shell]
disabled = false
heuristic = true
[jobs]
disabled = true
[container]
disabled = false
symbol = ''
format = '[\[$symbol $name\] ]($style)'

[php]
symbol = '󰟆 '

[docker_context]
disabled = true
[custom.podman]
command = "~/bin/starship-podman.sh"
description = "Podman"
symbol = '󰡨'
detect_files = [
    "docker-compose.yaml",
    "docker-compose.yml",
    "docker-compose.override.yaml",
    "docker-compose.override.yml",
    "Dockerfile",
    "Containerfile",
]
style = "blue bold"
format = "[$symbol $output]($style) "
