name: 'files'
services:

  explorer:
    image: 'nxzai/explorer:v2.0.2'
    restart: 'unless-stopped'
    environment:
      TZ: 'Europe/Amsterdam'
      NODE_ENV: 'production'
      PUBLIC_URL: 'https://files.lan.zanbaldwin.com'
      SEARCH_DEEP: 'false'
      EDITOR_EXTENSIONS: 'toml,dockerfile,makefile'
      PUID: '${PUID:-950}'
      PGID: '${PGID:-950}'
    ports:
      - target: 3000
        published: 3453
        protocol: 'tcp'
        host_ip: '127.0.0.1'
    volumes:
      - type: 'bind'
        source: '/mnt/fast/apps/explorer'
        target: '/config'
        read_only: false
      - type: 'bind'
        source: '/mnt/tank4/class1'
        target: '/mnt/Class1'
        read_only: true
      - type: 'bind'
        source: '/mnt/tank4/class2'
        target: '/mnt/Class2'
        read_only: false
