[cursor]
# Cursor blinking interval in milliseconds.
blink_interval = 750
# Time after which cursor stops blinking, in seconds.
# Specifying '0' will disable timeout for blinking.
blink_timeout = 5
# Thickness of the cursor relative to the cell width as floating point number
# from `0.0` to `1.0`.
thickness = 0.15
# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused.
unfocused_hollow = true
# Vi mode cursor style
# If the vi mode cursor style is `None` or not specified, it will fall back to
# the style of the active value of the normal cursor.
# See `cursor.style` for available options.
#vi_mode_style = "None"

[cursor.style]
# Values for `shape`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
shape = "Block"
# Values for `blinking`:
#   - Never: Prevent the cursor from ever blinking
#   - Off: Disable blinking by default
#   - On: Enable blinking by default
#   - Always: Force the cursor to always blink
blinking = "On"
