[debug]
# Highlight window damage information.
highlight_damage = false
# Values for `log_level`: Off, Error, Warn, Info, Debug, Trace
log_level = "Warn"
# Keep the log file after quitting Alacritty.
persistent_logging = false
# Print all received window events.
print_events = false
# Display the time it takes to redraw each frame.
render_timer = false
# Renderer override.
#   - glsl3
#   - gles2
#   - gles2_pure
renderer = "None"
