name: 'network'
services:

  tailscale:
    image: 'tailscale/tailscale:v1.90.9'
    restart: 'unless-stopped'
    network_mode: 'host'
    environment:
      TS_STATE_DIR: '/var/lib/tailscale'
      TS_AUTH_ONCE: 'true'
      TS_ENABLE_HEALTH_CHECK: 'true'
      TS_LOCAL_ADDR_PORT: '0.0.0.0:8575'
      TS_EXTRA_ARGS: '--accept-routes'
      TS_USERSPACE: 'false'
      TS_ACCEPT_DNS: 'true'
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --spider -q "http://127.0.0.1:8575/healthz"' ]
      interval: '30s'
      timeout: '5s'
      retries: 5
      start_period: '30s'
    configs:
      - source: 'init'
        target: '/init.sh'
    volumes:
      - type: 'volume'
        source: 'tailscale'
        target: '/var/lib/tailscale'
        read_only: false
    command: [ '/bin/sh', '/init.sh' ]
    devices:
      - '/dev/net/tun:/dev/net/tun'
    cap_add:
      - 'net_admin'
      - 'sys_module'

volumes:
  tailscale:
    driver: 'local'

configs:
  init:
    content: |
      #!/bin/sh
      # Prioritize LAN routes over Tailscale subnet routes
      ip rule add from 192.168.1.0/24 to 192.168.1.0/24 lookup main priority 5200 2>/dev/null || true
      # Ensure non-LAN traffic to 192.168.1.0/24 uses Tailscale
      ip rule add from all to 192.168.1.0/24 lookup 52 priority 5255 2>/dev/null || true
      echo "LAN routes prioritised..."
      exec /usr/local/bin/containerboot "$@"
