[user]
name = "Zan Baldwin"
email = "hello@zanbaldwin.com"

[git]
auto-local-branch = true
push-branch-prefix = "zanbaldwin/push-"

[template-aliases]
# Relative timestamp rendered as "x days/hours/seconds ago"
'format_timestamp(timestamp)' = 'timestamp.ago()'
# Show both author name and email address
'format_short_signature(signature)' = 'signature'
'format_short_id(id)' = 'id.shortest(12)'
log_comfortable = 'builtin_log_oneline ++ "\n"'

[ui]
diff-instructions = true
pager = ":builtin"
paginate = "never"
default-command = "status"
log-synthetic-elided-nodes = false

[format]
tree-level-conflicts = true

[aliases]
co = ["checkout"]
