# The bell is rung every time the BEL control character is received.
[bell]
# Animation effect for flashing the screen when the visual bell is rung.
#
# Values for `animation`:
#   - Ease
#   - EaseOut
#   - EaseOutSine
#   - EaseOutQuad
#   - EaseOutCubic
#   - EaseOutQuart
#   - EaseOutQuint
#   - EaseOutExpo
#   - EaseOutCirc
#   - Linear
animation = "EaseOutExpo"
# Visual bell animation color.
color = "#ffffff"
# Duration of the visual bell flash in milliseconds. A `duration` of `0` will
# disable the visual bell animation.
duration = 0

# This program is executed whenever the bell is rung. When set to
# `command: None`, no command will be executed.
#
# Example:
# [bell.command]
# program = "notify-send"
# args = ["Hello, World!"]
command = "None"
