ARG NOTEBOOK_VARIANT="pytorch"
ARG NOTEBOOK_VERSION="cuda12-latest"


# Evcxr: A Rust Jupyter Kernel
FROM "rust:latest" AS rust
RUN export EVCXR_LATEST_VERSION="$(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' 'https://github.com/evcxr/evcxr.git' \
        | \grep -v '\^' \
        | \grep -P -e '\d+\.\d+' \
        | \grep -P -v 'alpha|ALPHA|beta|BETA|rc|RC|-' \
        | cut -d'/' -f3 \
        | sort --version-sort \
        | tail -n1 \
    )" \
 && echo "Latest stable version of 'evcxr/evcxr' is ${EVCXR_LATEST_VERSION}" \
 && git clone "https://github.com/evcxr/evcxr.git" --depth=1 --branch="${EVCXR_LATEST_VERSION}" "/tmp/evcxr" \
 && (cd "/tmp/evcxr"; cargo build --release --bin "evcxr_jupyter") \
 && mkdir -p "/opt/evcxr" \
 && mv "/tmp/evcxr/target/release/evcxr_jupyter" "/opt/evcxr/evcxr_jupyter" \
 && rm -rf "/tmp/evcxr"


FROM "quay.io/jupyter/${NOTEBOOK_VARIANT}-notebook:${NOTEBOOK_VERSION}" as jupyter
ENV NOTEBOOK_ARGS="--ip='0.0.0.0' --no-browser --NotebookApp.token='' --NotebookApp.password='' --LabApp.token='' --LabApp.password=''"
# The base image has already switched to a non-root user, build evcxr in a
# separate container and copy it over rather than trying to build here.
COPY --from="rust" "/opt/evcxr/evcxr_jupyter" "/usr/bin/evcxr_jupyter"
# Rust and its components.
RUN (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y) \
 && . "${HOME}/.cargo/env" \
 && rustup component add "rust-src" \
 && "/usr/bin/evcxr_jupyter" --install
